# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore

concurrency: ci-${{ github.ref }}

jobs:
  format:
    uses: ./.github/workflows/format.yml

